# Generated by Django 2.2 on 2021-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_auto_20210519_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
