# Generated by Django 2.2 on 2021-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_observation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
