# Generated by Django 2.2 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_observation_search_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
